# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

# for non-orb configuration see old commit
# https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml

# to use CircleCI orbs need to use version >= 2.1
version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.16.1
  # for testing on Windows
  # https://circleci.com/docs/2.0/hello-world-windows/
  win: circleci/windows@1

jobs:
  win-test:
    working_directory: ~/app
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm ci
      - run: npm run cy:verify

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      # if you want to test execa's behavior on Windows
      # - run: node ./scripts/test-execa

      - run:
          name: 'Start server'
          command: npm run serve
          background: true

      - run:
          name: 'Run Cypress tests'
          command: npm run test:e2e:ci --env circle=true
          no_output_timeout: '1m'
      - store_artifacts:
          path: cypress\screenshots
      - store_artifacts:
          path: cypress\videos

workflows:
  win-build:
    jobs:
      - win-test

  linux-build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          name: 'Linux install'
          # and builds the app using this command
          #build: 'npm run build'
          #post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
          #  - run: npx cypress cache path
          #  - run: npx cypress cache list

      # runs on 1 machines, load balances tests
      # and records on Cypress Dashboard
      - cypress/run:
          # name this job because we are running "cypress/run" several times
          # with different parameters
          name: '1 machine'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          record: false # record results on Cypress dashboard
          parallel: false # load balance all tests
          parallelism: 1 # across 3 machines
          group: '1x-electron on CircleCI' # name this group
          start: 'npm run serve' # start server before running tests

      # run on 1 machines using Chrome browser
      - cypress/run:
          name: '1 machines using Chrome'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome76
          # use browser "chrome" for running tests
          browser: chrome
          record: false
          parallel: false
          parallelism: 1
          group: '1x-chrome on CircleCI'
          start: 'npm run serve'

      - cypress/run:
          name: '1 machines using Firefox'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome73-ff68
          # use browser "chrome" for running tests
          browser: firefox
          record: false
          parallel: false
          parallelism: 1
          group: '1x-firefox on CircleCI'
          start: 'npm run serve'

     # - release:
     #     filters:
     #       branches:
     #         only:
     #           - master
     #     requires:
     #       - 3 machines
